apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/helm-controller/releases/download/v0.28.0/helm-controller.crds.yaml
- https://github.com/fluxcd/helm-controller/releases/download/v0.28.0/helm-controller.deployment.yaml
- account.yaml
transformers:
- labels.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-controller
  path: patch.yaml
