site_name: Flux | GitOps Toolkit
site_description: Open and extensible continuous delivery solution for Kubernetes
site_author: The Flux project
site_url: https://toolkit.fluxcd.io

repo_name: fluxcd/flux2
repo_url: https://github.com/fluxcd/flux2
edit_uri: ""

theme:
  name: material
  logo: _files/flux-icon@2x.png
  language: en
  palette:
    primary: blue
    accent: indigo
  custom_dir: mkdocs/

docs_dir: docs

extra_css:
  - _static/custom.css

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.extra
  - pymdownx.progressbar
  - pymdownx.superfences:
      highlight_code: true
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Core Concepts: core-concepts/index.md
  - Get Started: get-started/index.md
  - Migration:
    - Migration and Support Timetable: migration/timetable.md
    - Migrate from Flux v1: guides/flux-v1-migration.md
    - Migrate from Flux v1 image update automation: guides/flux-v1-automation-migration.md
    - Migrate from the Helm Operator: guides/helm-operator-migration.md
    - FAQ: guides/faq-migration.md
  - Guides:
      - Installation: guides/installation.md
      - Manage Helm Releases: guides/helmreleases.md
      - Setup Notifications: guides/notifications.md
      - Setup Webhook Receivers: guides/webhook-receivers.md
      - Monitoring with Prometheus: guides/monitoring.md
      - Sealed Secrets: guides/sealed-secrets.md
      - Mozilla SOPS: guides/mozilla-sops.md
      - Automate image updates to Git: guides/image-update.md
      - Sortable image tags to use with automation: guides/sortable-image-tags.md
  - Toolkit Components:
    - Overview: components/index.md
    - Source Controller:
      - Overview: components/source/controller.md
      - GitRepository CRD: components/source/gitrepositories.md
      - HelmRepository CRD: components/source/helmrepositories.md
      - HelmChart CRD: components/source/helmcharts.md
      - Bucket CRD: components/source/buckets.md
      - Source API Reference: components/source/api.md
    - Kustomize Controller:
      - Overview: components/kustomize/controller.md
      - Kustomization CRD: components/kustomize/kustomization.md
      - Kustomize API Reference: components/kustomize/api.md
    - Helm Controller:
        - Overview: components/helm/controller.md
        - HelmRelease CRD: components/helm/helmreleases.md
        - Helm API Reference: components/helm/api.md
    - Notification Controller:
        - Overview: components/notification/controller.md
        - Event: components/notification/event.md
        - Provider CRD: components/notification/provider.md
        - Alert CRD: components/notification/alert.md
        - Receiver CRD: components/notification/receiver.md
        - Notification API Reference: components/notification/api.md
    - Image Automation Controllers:
        - Overview: components/image/controller.md
        - ImageRepository CRD: components/image/imagerepositories.md
        - ImagePolicy CRD: components/image/imagepolicies.md
        - ImageUpdateAutomation CRD: components/image/imageupdateautomations.md
        - Automation API Reference: components/image/automation-api.md
  - Flux CLI:
    - Overview: cmd/flux.md
    - Bootstrap: cmd/flux_bootstrap.md
    - Bootstrap github: cmd/flux_bootstrap_github.md
    - Bootstrap gitlab: cmd/flux_bootstrap_gitlab.md
    - Check: cmd/flux_check.md
    - Create: cmd/flux_create.md
    - Create kustomization: cmd/flux_create_kustomization.md
    - Create helmrelease: cmd/flux_create_helmrelease.md
    - Create source: cmd/flux_create_source.md
    - Create source git: cmd/flux_create_source_git.md
    - Create source helm: cmd/flux_create_source_helm.md
    - Create source bucket: cmd/flux_create_source_bucket.md
    - Create alert provider: cmd/flux_create_alert-provider.md
    - Create alert: cmd/flux_create_alert.md
    - Create receiver: cmd/flux_create_receiver.md
    - Create image: cmd/flux_create_image.md
    - Create image policy: cmd/flux_create_image_policy.md
    - Create image repository: cmd/flux_create_image_repository.md
    - Create image update: cmd/flux_create_image_update.md
    - Create tenant: cmd/flux_create_tenant.md
    - Create secret: cmd/flux_create_secret.md
    - Create secret git: cmd/flux_create_secret_git.md
    - Create secret helm: cmd/flux_create_secret_helm.md
    - Create secret tls: cmd/flux_create_secret_tls.md
    - Delete: cmd/flux_delete.md
    - Delete kustomization: cmd/flux_delete_kustomization.md
    - Delete helmrelease: cmd/flux_delete_helmrelease.md
    - Delete source: cmd/flux_delete_source.md
    - Delete source git: cmd/flux_delete_source_git.md
    - Delete source helm: cmd/flux_delete_source_helm.md
    - Delete source bucket: cmd/flux_delete_source_bucket.md
    - Delete image: cmd/flux_delete_image.md
    - Delete image policy: cmd/flux_delete_image_policy.md
    - Delete image repository: cmd/flux_delete_image_repository.md
    - Delete image update: cmd/flux_delete_image_update.md
    - Export: cmd/flux_export.md
    - Export kustomization: cmd/flux_export_kustomization.md
    - Export helmrelease: cmd/flux_export_helmrelease.md
    - Export source: cmd/flux_export_source.md
    - Export source git: cmd/flux_export_source_git.md
    - Export source helm: cmd/flux_export_source_helm.md
    - Export source bucket: cmd/flux_export_source_bucket.md
    - Export alert provider: cmd/flux_export_alert-provider.md
    - Export alert: cmd/flux_export_alert.md
    - Export receiver: cmd/flux_export_receiver.md
    - Export image: cmd/flux_export_image.md
    - Export image policy: cmd/flux_export_image_policy.md
    - Export image repository: cmd/flux_export_image_repository.md
    - Export image update: cmd/flux_export_image_update.md
    - Get: cmd/flux_get.md
    - Get kustomizations: cmd/flux_get_kustomizations.md
    - Get helmreleases: cmd/flux_get_helmreleases.md
    - Get sources: cmd/flux_get_sources.md
    - Get sources git: cmd/flux_get_sources_git.md
    - Get sources helm: cmd/flux_get_sources_helm.md
    - Get sources chart: cmd/flux_get_sources_chart.md
    - Get sources bucket: cmd/flux_get_sources_bucket.md
    - Get alert provider: cmd/flux_get_alert-provider.md
    - Get alerts: cmd/flux_get_alerts.md
    - Get alert providers: cmd/flux_get_alert-providers.md
    - Get receivers: cmd/flux_get_receivers.md
    - Get images: cmd/flux_get_images.md
    - Get images policy: cmd/flux_get_images_policy.md
    - Get images repository: cmd/flux_get_images_repository.md
    - Get images update: cmd/flux_get_images_update.md
    - Install: cmd/flux_install.md
    - Logs: cmd/flux_logs.md
    - Resume: cmd/flux_resume.md
    - Resume kustomization: cmd/flux_resume_kustomization.md
    - Resume helmrelease: cmd/flux_resume_helmrelease.md
    - Resume source: cmd/flux_resume_source.md
    - Resume source git: cmd/flux_resume_source_git.md
    - Resume source helm: cmd/flux_resume_source_helm.md
    - Resume source chart: cmd/flux_resume_source_chart.md
    - Resume source bucket: cmd/flux_resume_source_bucket.md
    - Resume alert provider: cmd/flux_resume_alert-provider.md
    - Resume alert: cmd/flux_resume_alert.md
    - Resume receiver: cmd/flux_resume_receiver.md
    - Resume image: cmd/flux_resume_image.md
    - Resume image repository: cmd/flux_resume_image_repository.md
    - Resume image update: cmd/flux_resume_image_update.md
    - Suspend: cmd/flux_suspend.md
    - Suspend kustomization: cmd/flux_suspend_kustomization.md
    - Suspend helmrelease: cmd/flux_suspend_helmrelease.md
    - Suspend source: cmd/flux_suspend_source.md
    - Suspend source git: cmd/flux_suspend_source_git.md
    - Suspend source helm: cmd/flux_suspend_source_helm.md
    - Suspend source chart: cmd/flux_suspend_source_chart.md
    - Suspend source bucket: cmd/flux_suspend_source_bucket.md
    - Suspend alert provider: cmd/flux_suspend_alert-provider.md
    - Suspend alert: cmd/flux_suspend_alert.md
    - Suspend receiver: cmd/flux_suspend_receiver.md
    - Suspend image: cmd/flux_suspend_image.md
    - Suspend image repository: cmd/flux_suspend_image_repository.md
    - Suspend image update: cmd/flux_suspend_image_update.md
    - Reconcile: cmd/flux_reconcile.md
    - Reconcile kustomization: cmd/flux_reconcile_kustomization.md
    - Reconcile helmrelease: cmd/flux_reconcile_helmrelease.md
    - Reconcile source: cmd/flux_reconcile_source.md
    - Reconcile source git: cmd/flux_reconcile_source_git.md
    - Reconcile source helm: cmd/flux_reconcile_source_helm.md
    - Reconcile source bucket: cmd/flux_reconcile_source_bucket.md
    - Reconcile image: cmd/flux_reconcile_image.md
    - Reconcile image repository: cmd/flux_reconcile_image_repository.md
    - Reconcile image update: cmd/flux_reconcile_image_update.md
    - Uninstall: cmd/flux_uninstall.md
  - Dev Guides:
      - Watching for source changes: dev-guides/source-watcher.md
      - Advanced debugging: dev-guides/debugging.md
  - Roadmap: roadmap/index.md
  - Contributing: contributing/index.md
  - FAQ: faq/index.md
