site_name: GitOps Toolkit
site_description: A toolkit for assembling GitOps pipelines on Kubernetes
site_author: The Flux CD contributors
site_url: https://toolkit.fluxcd.io

repo_name: fluxcd/toolkit
repo_url: https://github.com/fluxcd/toolkit
edit_uri: ""

theme:
  name: material
  logo: _files/flux-icon@2x.png
  language: en
  palette:
    primary: blue
    accent: indigo
  custom_dir: mkdocs/

docs_dir: docs

extra_css:
  - _static/custom.css

plugins:
  - search

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      highlight_code: true
  - pymdownx.tabbed
  - pymdownx.tilde

nav:
  - Introduction: index.md
  - Get Started: get-started/index.md
  - Guides:
      - Setup Notifications: guides/notifications.md
      - Setup Webhook Receivers: guides/webhook-receivers.md
  - Toolkit Components:
    - Source Controller:
      - Overview: components/source/controller.md
      - GitRepository CRD: components/source/gitrepositories.md
      - HelmRepository CRD: components/source/helmrepositories.md
      - Source API Reference: components/source/api.md
    - Kustomize Controller:
      - Overview: components/kustomize/controller.md
      - Kustomization CRD: components/kustomize/kustomization.md
      - Kustomize API Reference: components/kustomize/api.md
    - Notification Controller:
        - Overview: components/notification/controller.md
        - Event: components/notification/event.md
        - Provider CRD: components/notification/provider.md
        - Alert CRD: components/notification/alert.md
        - Receiver CRD: components/notification/receiver.md
        - Notification API Reference: components/notification/api.md
  - Toolkit CLI:
    - Overview: cmd/tk.md
    - Bootstrap: cmd/tk_bootstrap.md
    - Bootstrap github: cmd/tk_bootstrap_github.md
    - Bootstrap gitlab: cmd/tk_bootstrap_gitlab.md
    - Check: cmd/tk_check.md
    - Create: cmd/tk_create.md
    - Create kustomization: cmd/tk_create_kustomization.md
    - Create source: cmd/tk_create_source.md
    - Create source git: cmd/tk_create_source_git.md
    - Delete: cmd/tk_delete.md
    - Delete kustomization: cmd/tk_delete_kustomization.md
    - Delete source: cmd/tk_delete_source.md
    - Delete source git: cmd/tk_delete_source_git.md
    - Export: cmd/tk_export.md
    - Export kustomization: cmd/tk_export_kustomization.md
    - Export source: cmd/tk_export_source.md
    - Export source git: cmd/tk_export_source_git.md
    - Get: cmd/tk_get.md
    - Get kustomizations: cmd/tk_get_kustomizations.md
    - Get sources: cmd/tk_get_sources.md
    - Get sources git: cmd/tk_get_sources_git.md
    - Install: cmd/tk_install.md
    - Resume: cmd/tk_resume.md
    - Resume kustomization: cmd/tk_resume_kustomization.md
    - Suspend: cmd/tk_suspend.md
    - Suspend kustomization: cmd/tk_suspend_kustomization.md
    - Sync: cmd/tk_sync.md
    - Sync kustomization: cmd/tk_sync_kustomization.md
    - Sync source: cmd/tk_sync_source.md
    - Sync source git: cmd/tk_sync_source_git.md
    - Uninstall: cmd/tk_uninstall.md
  - Roadmap: roadmap/index.md
  - Contributing: contributing/index.md
  - Dev Guides:
      - Watching for source changes: dev-guides/source-watcher.md
