site_name: GitOps Toolkit
site_description: A toolkit for assembling GitOps pipelines on Kubernetes
site_author: The Flux CD contributors
site_url: https://toolkit.fluxcd.io

repo_name: fluxcd/flux2
repo_url: https://github.com/fluxcd/flux2
edit_uri: ""

theme:
  name: material
  logo: _files/flux-icon@2x.png
  language: en
  palette:
    primary: blue
    accent: indigo
  custom_dir: mkdocs/

docs_dir: docs

extra_css:
  - _static/custom.css

plugins:
  - search

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences:
      highlight_code: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: index.md
  - Get Started: get-started/index.md
  - Guides:
      - Installation: guides/installation.md
      - Manage Helm Releases: guides/helmreleases.md
      - Setup Notifications: guides/notifications.md
      - Setup Webhook Receivers: guides/webhook-receivers.md
      - Monitoring with Prometheus: guides/monitoring.md
      - Sealed Secrets: guides/sealed-secrets.md
      - Mozilla SOPS: guides/mozilla-sops.md
  - Toolkit Components:
    - Source Controller:
      - Overview: components/source/controller.md
      - GitRepository CRD: components/source/gitrepositories.md
      - HelmRepository CRD: components/source/helmrepositories.md
      - HelmChart CRD: components/source/helmcharts.md
      - Bucket CRD: components/source/buckets.md
      - Source API Reference: components/source/api.md
    - Kustomize Controller:
      - Overview: components/kustomize/controller.md
      - Kustomization CRD: components/kustomize/kustomization.md
      - Kustomize API Reference: components/kustomize/api.md
    - Helm Controller:
        - Overview: components/helm/controller.md
        - HelmRelease CRD: components/helm/helmreleases.md
        - Helm API Reference: components/helm/api.md
    - Notification Controller:
        - Overview: components/notification/controller.md
        - Event: components/notification/event.md
        - Provider CRD: components/notification/provider.md
        - Alert CRD: components/notification/alert.md
        - Receiver CRD: components/notification/receiver.md
        - Notification API Reference: components/notification/api.md
  - Toolkit CLI:
    - Overview: cmd/flux.md
    - Bootstrap: cmd/flux_bootstrap.md
    - Bootstrap github: cmd/flux_bootstrap_github.md
    - Bootstrap gitlab: cmd/flux_bootstrap_gitlab.md
    - Check: cmd/flux_check.md
    - Create: cmd/flux_create.md
    - Create kustomization: cmd/flux_create_kustomization.md
    - Create helmrelease: cmd/flux_create_helmrelease.md
    - Create source: cmd/flux_create_source.md
    - Create source git: cmd/flux_create_source_git.md
    - Create source helm: cmd/flux_create_source_helm.md
    - Create source bucket: cmd/flux_create_source_bucket.md
    - Create alert provider: cmd/flux_create_alert-provider.md
    - Create alert: cmd/flux_create_alert.md
    - Create receiver: cmd/flux_create_receiver.md
    #- Create tenant: cmd/flux_create_tenant.md
    - Delete: cmd/flux_delete.md
    - Delete kustomization: cmd/flux_delete_kustomization.md
    - Delete helmrelease: cmd/flux_delete_helmrelease.md
    - Delete source: cmd/flux_delete_source.md
    - Delete source git: cmd/flux_delete_source_git.md
    - Delete source helm: cmd/flux_delete_source_helm.md
    - Delete source bucket: cmd/flux_delete_source_bucket.md
    - Export: cmd/flux_export.md
    - Export kustomization: cmd/flux_export_kustomization.md
    - Export helmrelease: cmd/flux_export_helmrelease.md
    - Export source: cmd/flux_export_source.md
    - Export source git: cmd/flux_export_source_git.md
    - Export source helm: cmd/flux_export_source_helm.md
    - Export source bucket: cmd/flux_export_source_bucket.md
    - Export alert provider: cmd/flux_export_alert-provider.md
    - Export alert: cmd/flux_export_alert.md
    - Export receiver: cmd/flux_export_receiver.md
    - Get: cmd/flux_get.md
    - Get kustomizations: cmd/flux_get_kustomizations.md
    - Get helmreleases: cmd/flux_get_helmreleases.md
    - Get sources: cmd/flux_get_sources.md
    - Get sources git: cmd/flux_get_sources_git.md
    - Get sources helm: cmd/flux_get_sources_helm.md
    - Get sources bucket: cmd/flux_get_sources_bucket.md
    - Get alert provider: cmd/flux_get_alert-provider.md
    - Get alert: cmd/flux_get_alert.md
    - Get receiver: cmd/flux_get_receiver.md
    - Install: cmd/flux_install.md
    - Resume: cmd/flux_resume.md
    - Resume kustomization: cmd/flux_resume_kustomization.md
    - Resume helmrelease: cmd/flux_resume_helmrelease.md
    - Resume alert provider: cmd/flux_resume_alert-provider.md
    - Resume alert: cmd/flux_resume_alert.md
    - Resume receiver: cmd/flux_resume_receiver.md
    - Suspend: cmd/flux_suspend.md
    - Suspend kustomization: cmd/flux_suspend_kustomization.md
    - Suspend helmrelease: cmd/flux_suspend_helmrelease.md
    - Suspend alert provider: cmd/flux_suspend_alert-provider.md
    - Suspend alert: cmd/flux_suspend_alert.md
    - Suspend receiver: cmd/flux_suspend_receiver.md
    - Reconcile: cmd/flux_reconcile.md
    - Reconcile kustomization: cmd/flux_reconcile_kustomization.md
    - Reconcile helmrelease: cmd/flux_reconcile_helmrelease.md
    - Reconcile source: cmd/flux_reconcile_source.md
    - Reconcile source git: cmd/flux_reconcile_source_git.md
    - Reconcile source helm: cmd/flux_reconcile_source_helm.md
    - Reconcile source bucket: cmd/flux_reconcile_source_bucket.md
    - Uninstall: cmd/flux_uninstall.md
  - Roadmap: roadmap/index.md
  - Contributing: contributing/index.md
  - Dev Guides:
      - Watching for source changes: dev-guides/source-watcher.md
  - FAQ: faq/index.md
