apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/fluxcd/source-controller/releases/download/v1.0.0-rc.4/source-controller.crds.yaml
- https://github.com/fluxcd/kustomize-controller/releases/download/v1.0.0-rc.4/kustomize-controller.crds.yaml
- https://github.com/fluxcd/helm-controller/releases/download/v0.34.0/helm-controller.crds.yaml
- https://github.com/fluxcd/notification-controller/releases/download/v1.0.0-rc.4/notification-controller.crds.yaml
- https://github.com/fluxcd/image-reflector-controller/releases/download/v0.28.0/image-reflector-controller.crds.yaml
- https://github.com/fluxcd/image-automation-controller/releases/download/v0.34.0/image-automation-controller.crds.yaml
