name: backport
on:
  pull_request_target:
    types: [closed, labeled]
permissions: read-all
jobs:
  backport:
    permissions:
      contents: write # for reading and creating branches.
      pull-requests: write # for creating pull requests against release branches.
    uses: fluxcd/gha-workflows/.github/workflows/backport.yaml@v0.4.0
    secrets:
      github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
