name: sync-labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yaml
permissions: read-all
jobs:
  sync-labels:
    permissions:
      contents: read # for reading the labels file.
      issues: write # for creating and updating labels.
    uses: fluxcd/gha-workflows/.github/workflows/labels-sync.yaml@v0.4.0
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
